/** Create chat actions */

module.exports = {
    COMMUNITY_CHAT: "COMMUNITY_CHAT",
    USER_CONNECTED: "USER_CONNECTED",
    USER_DISCONNECTED: "USER_DISCONNECTED",
    VERIFY_USER: "VERIFY_USER",
    MESSAGE_RECIEVED: "MESSAGE_RECIEVED",
    MESSAGE_SENT: "MESSAGE_SENT",
    TYPING: "TYPING",
    LOGOUT: "LOGOUT"
}